//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRRInvoice
    {
        public int DRRInvoiceID { get; set; }
        public Nullable<int> DRRID { get; set; }
        public Nullable<int> RecPayID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Remarks { get; set; }
    }
}
