//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InScanNew
    {
        public int InScanID { get; set; }
        public string AWBNo { get; set; }
        public decimal CourierCharge { get; set; }
        public Nullable<decimal> OtherCharge { get; set; }
        public string Consignee { get; set; }
        public string Consignor { get; set; }
        public string OriginLocation { get; set; }
        public string DestinationLocation { get; set; }
        public string CourierType { get; set; }
        public Nullable<decimal> CBM { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Pieces { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> NetTotal { get; set; }
        public string FAgent { get; set; }
        public string FAWBNo { get; set; }
        public string NCND { get; set; }
        public string Branch { get; set; }
        public string ReceivedBy { get; set; }
        public string CollectedBy { get; set; }
        public int ImportID { get; set; }
    }
}
