//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCPaymentReceipt
    {
        public int McPaymentReceiptID { get; set; }
        public Nullable<int> InscanID { get; set; }
        public string AWBNo { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public string PayVoucherNo { get; set; }
        public Nullable<int> PayAcHeadID { get; set; }
        public Nullable<int> PayAcjournalID { get; set; }
        public Nullable<decimal> PayAmt { get; set; }
        public string PayType { get; set; }
        public Nullable<int> PayBankID { get; set; }
        public string PayChequeNo { get; set; }
        public Nullable<System.DateTime> PayChequeDate { get; set; }
        public string PayRemarks { get; set; }
        public string RecType { get; set; }
        public Nullable<System.DateTime> RecDate { get; set; }
        public string RecVoucherNo { get; set; }
        public Nullable<int> RecAcHeadID { get; set; }
        public Nullable<int> RecAcjournalID { get; set; }
        public Nullable<decimal> RecAmt { get; set; }
        public string RecChequeNo { get; set; }
        public Nullable<System.DateTime> RecChequeDate { get; set; }
        public string RecRemarks { get; set; }
        public Nullable<int> RecBankID { get; set; }
        public Nullable<int> FYearID { get; set; }
        public Nullable<int> AcCompanyID { get; set; }
    }
}
