//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentInvoiceDetail
    {
        public int ShipmentInvoiceDetailID { get; set; }
        public Nullable<int> ShipmentImportDetailID { get; set; }
        public Nullable<int> ShipmentInvoiceID { get; set; }
        public Nullable<decimal> InvoiceValue { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> TaxP { get; set; }
        public Nullable<decimal> adminCharges { get; set; }
    }
}
