//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempRateDetail
    {
        public decimal RateMasterID { get; set; }
        public Nullable<decimal> RateSlabNo { get; set; }
        public Nullable<decimal> IncrementWeight { get; set; }
        public Nullable<decimal> LowerWeight { get; set; }
        public Nullable<decimal> UpperWeight { get; set; }
        public Nullable<decimal> CustomerRate { get; set; }
    }
}
