//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempRateMaster
    {
        public decimal RateMasterID { get; set; }
        public string CustomerCode { get; set; }
        public string FAgentCode { get; set; }
        public string ProductCode { get; set; }
        public int ZoneCode { get; set; }
        public string CountryCode { get; set; }
        public string LocationCode { get; set; }
    }
}
