//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempInScan
    {
        public string awbno { get; set; }
        public Nullable<System.DateTime> InScanDate { get; set; }
        public int DepartmentID { get; set; }
        public string ConsignorCode { get; set; }
        public string ConsignorName { get; set; }
        public string ConsigneeName { get; set; }
        public string OriginID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string DestinationID { get; set; }
        public int CustomerRateTypeID { get; set; }
        public string Pieces { get; set; }
        public Nullable<decimal> StatedWeight { get; set; }
        public string CashCredit { get; set; }
        public int CourierDescriptioID { get; set; }
        public string ServiceCode { get; set; }
        public string CollectedBy { get; set; }
        public int ReceivedBy { get; set; }
        public Nullable<decimal> CourierCharge { get; set; }
        public Nullable<decimal> OtherCharge { get; set; }
        public string remarks { get; set; }
        public int CourierStatusID { get; set; }
        public string StatusPaymentMode { get; set; }
        public int StatusClose { get; set; }
        public int StatusPickup { get; set; }
        public int StatusReconciled { get; set; }
        public decimal MaterialCost { get; set; }
        public string StatusInScan { get; set; }
        public string PODReceiverName { get; set; }
        public Nullable<System.DateTime> PODDate { get; set; }
        public string ShipperCode { get; set; }
        public string ShipperName { get; set; }
        public string FAgentID { get; set; }
        public string ForwardingAWBNo { get; set; }
        public decimal ForwardingCharge { get; set; }
    }
}
