//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempCommission
    {
        public int TempCommissionID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> TotalPickup { get; set; }
        public Nullable<int> TotalDelivery { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string InvoiceType { get; set; }
    }
}
